DB:
  url: "mongodb://root:root@localhost:27017"
  dbname: "TripWithMe"
  collection: "users"

Server:
  Port: 3004

App:
  name: "TripWithMe-Authenticate-Service"

SWAGGER:
  HOST: ${SWAGGER_HOST}

JWT:
  Secret: ${JWT_SECRET}
  Expired: 1h
  RefreshSecret: refreshSecret
  RefreshExpired: 168h
